### PR TITLE
Adding support for #23 and workflow badge on README

### PR DESCRIPTION
**Pull request by gbrandtio**
- Added support for replacement of common issues with letters, which was proposed on https://github.com/esentis/string_extensions/issues/23.
- Added test workflow badge on README.

### CODE REVIEW

**Review by esentis — CHANGES_REQUESTED** [review]
Hello! I suggest that we do not close #23, as there are many symbols that can be used to represent letters in addition to those covered by the proposed method. A helpful reference for such symbols can be found at the following link: https://en.wikipedia.org/wiki/Leet. Thank you!

The build badge is welcome though if you fix the PR :)

**Comment by gbrandtio** [comment]
Oh gosh, I wasn't aware of that - looked simpler 😄

**Comment by gbrandtio** [comment]
So @esentis do you suggest to revert, or to extend the PR to include the additional symbols ?

**Comment by esentis** [comment]
I recommend that we revert it yes.

**Review by esentis — APPROVED** [review]

**Pull request merged**
