### PR TITLE
StringHelpers & small bugfixes

### PR DESCRIPTION
**Pull request by zonaro**
- Add `StringHelpers` class (contains getters for common strings)
 - Add md5 getter
 - Small bugfixes on `RemoveFirstAny`, and `RemoveLastAny`
 - Reworked `IsOpenWrapChar` and `IsCloseWrapChar` (Use `StringHelpers`)

### CODE REVIEW

**Comment by zonaro** [comment]
Can i import packages like crypto? I have the following code and I think it makes sense to integrate with string_extensions

```dart
import 'dart:convert';
import 'package:convert/convert.dart';
import 'package:crypto/crypto.dart' as crypto;
import 'package:string_extensions/string_extensions.dart';

extension OtherMiscExtensions on String? {
  // Return a MD5 hash of current `String`
  String? get md5 {
    String? data = this;
    if (data.isNotBlank) {
      var content = const Utf8Encoder().convert(data!);
      var md5 = crypto.md5;
      var digest = md5.convert(content);
      data = hex.encode(digest.bytes);
    }
    return data;
  }
}
```

If you agree, I add and do a PR

**Comment by esentis** [comment]
Hey thanks again for the contribution! I think we are ok with ‘crypto’. However let’s not create many dependencies to foreign packages.

**Comment by zonaro** [comment]
I also don't like external dependencies on these kind of packages (extension packages). I'm new to flutter, so I preferred to confirm beforehand if crypto was some external dependency. I will make a pull request then

**Comment by esentis** [comment]
I will merge it for now, if we get projects breaking due to dependency issues we will remove `md5` method. Cheers.

**Pull request merged**
